### GET welcome ok
GET http://localhost:8080/welcome
Authorization: Basic username password

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### GET welcome unauth
GET http://localhost:8080/welcome
Authorization: Basic username badpassword

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 401, "Response status is not 401");
});
%}

### GET invalid request
GET http://localhost:8080/unwelcome
Authorization: Basic username password

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}
